@startuml
abstract class Dakoku {
    - {abstract} dakokuUrl: String
}

class JcDakoku extends Dakoku {

}

class RDakoku extends Dakoku {

}

abstract class Login {
    - {abstract} loginUrl: String
    - {abstract} loginIdField: String
    - {abstract} loginPassField: String

    + getLoginUrl(): String
    + getLoginField(): String
    + getLoginPassField(): String
}

@enduml