"@startuml Dakoku Class図"

package utility {
    enum MyUrls {
        JC_LOGIN_URL
        JC_DAKOKU_URL
        R_LOGIN_URL
        R_DAKOKU_URL
    }

    enum JcInformations {
    
        JC_LOGIN_ID_FIELD
        JC_LOGIN_PASS_FIELD
        JC_LOGIN_BUTTON_FIELD

        JC_DAKOKU_BUTTON_IN
        JC_DAKOKU_BUTTON_OUT
    
    }
enum RInformations {
        R_LOGIN_ID_FIELD
        R_LOGIN_PASS_FIELD
        R_LOGIN_BUTTON_FIELD
        
        R_DAKOKU_LIST_BUTTON
        R_DAKOKU_BUTTON_IN
        R_DAKOKU_BUTTON_OUT
    }
}
package login {
    abstract class Login {
        - loginUrl: String
        - loginIdField: By
        - loginPassField: By
        - loginButton: By
        ~ driver: Webdriver

        - accessLoginPage(): void
        - sendLoginIdToField(): void
        - sendLoginPassToField(): void
        - pushLoginButton(): void 
        + login(): void
        + getDriver(): Webdriver
    }

    class JcLogin extends Login {
        - jcLogin: Login
        - JcLogin
        + getInstance(): Login
    }

    class RLogin extends Login {
        - rLogin: Login
        - RLogin
        + getInstance(): Login
    }
}

package run {
    class main {

    }
}

package dakoku {
    abstract class Dakoku {
        
    }
}



@enduml